post:
  summary: Hashrate Resale Request (USER_DATA)
  description: 'Weight(IP): 5'
  tags:
  - Mining
  parameters:
  - $ref: ../components/parameters/userName.yaml
  - $ref: ../components/parameters/algo.yaml
  - $ref: ../components/parameters/startDate.yaml
  - $ref: ../components/parameters/endDate.yaml
  - $ref: ../components/parameters/toPoolUser.yaml
  - $ref: ../components/parameters/hashRate.yaml
  - $ref: ../components/parameters/recvWindow.yaml
  - $ref: ../components/parameters/timestamp.yaml
  - $ref: ../components/parameters/signature.yaml
  security:
  - ApiKeyAuth: []
  responses:
    '200':
      $ref: ../components/responses/sapi_mining_hash-transfer_config_v1_200.yaml
    '400':
      $ref: ../components/responses/sapi_mining_hash-transfer_config_v1_400.yaml
    '401':
      $ref: ../components/responses/sapi_mining_hash-transfer_config_v1_401.yaml
