get:
  summary: All Coins' Information (USER_DATA)
  description: 'Get information of coins (available for deposit and withdraw) for
    user.


    Weight(IP): 10'
  tags:
  - Wallet
  parameters:
  - $ref: ../components/parameters/recvWindow.yaml
  - $ref: ../components/parameters/timestamp.yaml
  - $ref: ../components/parameters/signature.yaml
  security:
  - ApiKeyAuth: []
  responses:
    '200':
      $ref: ../components/responses/sapi_capital_config_getall_v1_200.yaml
    '400':
      $ref: ../components/responses/sapi_capital_config_getall_v1_400.yaml
    '401':
      $ref: ../components/responses/sapi_capital_config_getall_v1_401.yaml
