paths:
  /sapi/v1/mining/hash-transfer/config:
    post:
      summary: Hashrate Resale Request (USER_DATA)
      description: 'Weight(IP): 5'
      tags:
      - Mining
      parameters:
      - $ref: ..\..\parameters/userName.yaml
      - $ref: ..\..\parameters/algo.yaml
      - $ref: ..\..\parameters/startDate.yaml
      - $ref: ..\..\parameters/endDate.yaml
      - $ref: ..\..\parameters/toPoolUser.yaml
      - $ref: ..\..\parameters/hashRate.yaml
      - $ref: ..\..\parameters/recvWindow.yaml
      - $ref: ..\..\parameters/timestamp.yaml
      - $ref: ..\..\parameters/signature.yaml
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          $ref: ..\..\responses/config_post_200.yaml
        '400':
          $ref: ..\..\responses/config_post_400.yaml
        '401':
          $ref: ..\..\responses/config_post_401.yaml
